nginx:
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
        - node3:node3
    ports:
        - "80:80"
node1:
    build: ./node
    links:
        - redis
        - sidecar
    ports:
        - "8080"
node2:
    build: ./node
    links:
        - redis
        - sidecar
    ports:
        - "8080"
node3:
    build: ./node
    links:
        - redis
        - sidecar
    ports:
        - "8080"
sidecar:
  build: ./side-car
  ports:
      - "4000"
redis:
    image: redis
    ports:
        - "6379"
